spring.application.name=animetoanime

spring.datasource.url=jdbc:postgresql://localhost:5432/animetoanime
spring.datasource.username=postgres
#spring.datasource.password= in env file

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.types-contibutor = false

# passwords included here:
spring.config.import=./env.properties